version: '3.8'
services:
  web:
    build: .
    command: gunicorn travel_booking.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=travel_booking.settings
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: travel_db
      MYSQL_USER: travel_user
      MYSQL_PASSWORD: travel_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
